
jobs:
  fedora-26/tox:
    requires: []
    priority: 50
    job:
      class: ToxTests
      args:
        git_repo: '{git_repo}'
        template: 
          name: felipevolpone/ci-pr13-f26
          version: 0.2.0
        timeout: 3600