topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 5750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 6700
  ad: &ad
    name: ad
    cpu: 6
    memory: 8000

jobs:
  fedora-27/ad_tests:
    requires: []
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_idviews.py
        template: &ci-master-f27
          name: freeipa/ci-master-f27
          version: 1.0.2
        timeout: 8000
        topology: *ad
