topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 5750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 6700
  huge_test: &huge_test
    name: huge_test
    cpu: 20
    memory: 32000

jobs:
  fedora-26/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f26
          name: freeipa/ci-master-f26
          version: 0.1.7
        timeout: 1800
        topology: *build

  fedora-26/serverdel:
    requires: [fedora-26/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-26/build_url}'
        test_suite: test_integration/test_server_del.py
        template: *ci-master-f26
        timeout: 3600
        topology: *master_1repl

  fedora-26/external_ca:
    requires: [fedora-26/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-26/build_url}'
        test_suite: test_integration/test_external_ca.py::TestExternalCA
        template: *ci-master-f26
        timeout: 3600
        topology: *master_1repl
